@host = http://localhost:3090/api

###
GET {{host}}/health
Content-Type: application/json

####################
# Students
####################
POST {{host}}/students HTTP/1.1
Content-Type: application/json

{
    "first_name": "Joe",
    "last_name": "Kim",
    "gender": "Male",
    "birth_date": "1997-08-22T00:00:00.000Z",
    "email": "joekim@coregate.dev",
    "phone_number": "0647951994"
}

###
GET {{host}}/students HTTP/1.1
Content-Type: application/json

###
GET {{host}}/students/1 HTTP/1.1
Content-Type: application/json

###
PATCH {{host}}/students/1 HTTP/1.1
Content-Type: application/json

{
    "email": "joekim@coregate.dev",
    "phone_number": "0647951994"
}

####################
# Teachers
####################
POST {{host}}/teachers HTTP/1.1
Content-Type: application/json

{
    "first_name": "Karina",
    "last_name": "Yoo",
    "gender": "Female",
    "birth_date": "1997-08-22T00:00:00.000Z",
    "email": "karina@coregate.dev",
    "phone_number": "0647951994"
}

###
GET {{host}}/teachers HTTP/1.1
Content-Type: application/json

###
GET {{host}}/teachers/1 HTTP/1.1
Content-Type: application/json

###
PATCH {{host}}/teachers/1 HTTP/1.1
Content-Type: application/json

{
    "phone_number": ""
}

####################
# Course Categories
####################
POST {{host}}/course-categories HTTP/1.1
Content-Type: application/json

{
    "name": "Sport",
    "short_name": "SPO"
}

###
GET {{host}}/course-categories HTTP/1.1
Content-Type: application/json

###
GET {{host}}/course-categories/2 HTTP/1.1
Content-Type: application/json

###
PATCH {{host}}/course-categories/1 HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "short_name": ""
}

###
DELETE {{host}}/course-categories/1 HTTP/1.1

####################
# Courses
####################
GET  {{host}}/courses HTTP/1.1
Content-Type: application/json

###
POST {{host}}/courses HTTP/1.1
Content-Type: application/json

{
    "name": "Calculus II",
    "level": 2,
    "teacher_id": 1,
    "category_id": 3
}

###
GET {{host}}/courses HTTP/1.1
Content-Type: application/json

###
GET  {{host}}/courses/1 HTTP/1.1
Content-Type: application/json

###
PATCH {{host}}/courses/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Cal 2"
}

###
DELETE {{host}}/courses/1 HTTP/1.1

####################
# Register Courses
####################
POST {{host}}/register-course HTTP/1.1
Content-Type: : application/json

{
    "student_id": 1,
    "course_id": 1
}

###
GET {{host}}/register-course HTTP/1.1

###
GET {{host}}/register-course/1 HTTP/1.1

###
DELETE {{host}}/register/course/1 HTTP/1.1
